using System.Collections.Generic;
using GameDevProject.Core;
using GameDevProject.Core.enemies;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;

namespace GameDevProject.Map.levels;

public class Level2 : ILevel
{
    private GameManager _game;
    public TileMap.Tiles?[,] GameMap { get; set; } =
    {
        { null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null },
        { null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null },
        { null, null, TileMap.Tiles.PURPLE_GRAVESTONE, null, null, null, null, null, null, null, TileMap.Tiles.PURPLE_GRASS_TOP_LEFT, TileMap.Tiles.PURPLE_GRASS_TOP_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_FLOATING_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_FLOATING_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_FLOATING_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_FLOATING_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_FLOATING_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_FLOATING_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_FLOATING_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_FLOATING_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_FLOATING_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_RIGHT, null, null, null, TileMap.Tiles.PURPLE_GRASS_TOP_ALONE, null, TileMap.Tiles.PURPLE_GRASS_TOP_LEFT },
        { TileMap.Tiles.PURPLE_GRASS_TOP_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_FLOATING_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_FLOATING_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_FLOATING_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_FLOATING_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_FLOATING_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_FLOATING_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_FLOATING_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_FLOATING_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_FLOATING_CENTER, TileMap.Tiles.PURPLE_DIRT_BOTTOM_CENTER, TileMap.Tiles.PURPLE_DIRT_BOTTOM_RIGHT, null, null, null, null, null, null, TileMap.Tiles.PURPLE_DIRT_MIDDLE_FLOATING_CENTER, null, null, null, TileMap.Tiles.PURPLE_DIRT_BOTTOM_LEFT, TileMap.Tiles.PURPLE_GRASS_TOP_FLOATING_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_FLOATING_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_FLOATING_CENTER, TileMap.Tiles.PURPLE_DIRT_BOTTOM_RIGHT, null, TileMap.Tiles.PURPLE_DIRT_BOTTOM_LEFT },
        { TileMap.Tiles.PURPLE_DIRT_MIDDLE_RIGHT, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, TileMap.Tiles.PURPLE_DIRT_MIDDLE_FLOATING_CENTER, null, null, null, null, null, null, null, null, null, null },
        { TileMap.Tiles.PURPLE_DIRT_MIDDLE_RIGHT, null, null, null, null, null, null, null, null, null, null, null, null, null, null, TileMap.Tiles.PURPLE_GRASS_TOP_ALONE, null, null, TileMap.Tiles.PURPLE_DIRT_MIDDLE_FLOATING_CENTER, null, null, null, null, null, null, null, null, null, null },
        { TileMap.Tiles.PURPLE_DIRT_MIDDLE_RIGHT, null, null, null, null, null, null, null, null, null, null, null, null, null, null, TileMap.Tiles.PURPLE_DIRT_MIDDLE_LEFT, TileMap.Tiles.PURPLE_GRASS_TOP_FLOATING_RIGHT, null, TileMap.Tiles.PURPLE_DIRT_MIDDLE_FLOATING_CENTER, null, null, null, TileMap.Tiles.PURPLE_GRAVESTONE, null, null, null, null, null, null },
        { TileMap.Tiles.PURPLE_DIRT_MIDDLE_RIGHT, null, null, null, TileMap.Tiles.PURPLE_GRASS_TOP_FLOATING_LEFT, TileMap.Tiles.PURPLE_GRASS_TOP_RIGHT, null, null, null, null, null, null, TileMap.Tiles.PURPLE_GRASS_TOP_LEFT, TileMap.Tiles.PURPLE_GRASS_TOP_FLOATING_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_FLOATING_CENTER, TileMap.Tiles.PURPLE_DIRT_MIDDLE_RIGHT, null, null, TileMap.Tiles.PURPLE_DIRT_MIDDLE_FLOATING_CENTER, null, TileMap.Tiles.PURPLE_GRASS_TOP_FLOATING_LEFT, TileMap.Tiles.PURPLE_GRASS_TOP_FLOATING_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_FLOATING_RIGHT, null, null, TileMap.Tiles.PURPLE_GRASS_TOP_FLOATING_LEFT, TileMap.Tiles.PURPLE_GRASS_TOP_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_FLOATING_CENTER },
        { TileMap.Tiles.PURPLE_DIRT_MIDDLE_RIGHT, null, null, null, null, TileMap.Tiles.PURPLE_DIRT_MIDDLE_FLOATING_CENTER, null, null, null, null, null, null, TileMap.Tiles.PURPLE_DIRT_MIDDLE_FLOATING_CENTER, null, null, TileMap.Tiles.PURPLE_DIRT_MIDDLE_FLOATING_CENTER, null, TileMap.Tiles.PURPLE_GRASS_TOP_FLOATING_LEFT, TileMap.Tiles.PURPLE_DIRT_MIDDLE_RIGHT, null, null, null, TileMap.Tiles.PURPLE_DIRT_MIDDLE_FLOATING_CENTER, null, null, null, null, TileMap.Tiles.PURPLE_DIRT_MIDDLE_FLOATING_CENTER, null },
        { TileMap.Tiles.PURPLE_DIRT_MIDDLE_RIGHT, null, null, null, null, TileMap.Tiles.PURPLE_DIRT_BOTTOM_LEFT, TileMap.Tiles.PURPLE_GRASS_TOP_FLOATING_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_RIGHT, null, null, TileMap.Tiles.PURPLE_GRASS_TOP_LEFT, TileMap.Tiles.PURPLE_GRASS_TOP_FLOATING_CENTER, TileMap.Tiles.PURPLE_DIRT_BOTTOM_RIGHT, null, null, TileMap.Tiles.PURPLE_DIRT_MIDDLE_FLOATING_CENTER, null, null, TileMap.Tiles.PURPLE_DIRT_MIDDLE_FLOATING_CENTER, null, null, null, TileMap.Tiles.PURPLE_DIRT_MIDDLE_FLOATING_CENTER, null, null, null, null, TileMap.Tiles.PURPLE_DIRT_MIDDLE_FLOATING_CENTER, null },
        { TileMap.Tiles.PURPLE_DIRT_MIDDLE_RIGHT, null, null, null, null, null, null, TileMap.Tiles.PURPLE_DIRT_MIDDLE_FLOATING_CENTER, null, null, TileMap.Tiles.PURPLE_DIRT_MIDDLE_FLOATING_CENTER, null, null, null, null, TileMap.Tiles.PURPLE_DIRT_MIDDLE_LEFT, TileMap.Tiles.PURPLE_GRASS_TOP_FLOATING_RIGHT, null, TileMap.Tiles.PURPLE_DIRT_MIDDLE_LEFT, TileMap.Tiles.PURPLE_GRASS_TOP_FLOATING_RIGHT, null, null, TileMap.Tiles.PURPLE_DIRT_MIDDLE_FLOATING_CENTER, null, null, null, null, TileMap.Tiles.PURPLE_DIRT_MIDDLE_FLOATING_CENTER, null },
        { TileMap.Tiles.PURPLE_DIRT_MIDDLE_RIGHT, null, null, null, null, null, null, TileMap.Tiles.PURPLE_DIRT_MIDDLE_LEFT, TileMap.Tiles.PURPLE_GRASS_TOP_FLOATING_RIGHT, null, TileMap.Tiles.PURPLE_DIRT_MIDDLE_FLOATING_CENTER, null, null, null, null, TileMap.Tiles.PURPLE_DIRT_MIDDLE_FLOATING_CENTER, null, null, TileMap.Tiles.PURPLE_DIRT_MIDDLE_FLOATING_CENTER, null, null, null, TileMap.Tiles.PURPLE_DIRT_MIDDLE_FLOATING_CENTER, null, null, TileMap.Tiles.PURPLE_GRASS_TOP_FLOATING_LEFT, TileMap.Tiles.PURPLE_GRASS_TOP_FLOATING_CENTER, TileMap.Tiles.PURPLE_DIRT_MIDDLE_RIGHT, null },
        { TileMap.Tiles.PURPLE_DIRT_MIDDLE_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_RIGHT, null, null, null, null, TileMap.Tiles.PURPLE_DIRT_MIDDLE_FLOATING_CENTER, null, null, TileMap.Tiles.PURPLE_DIRT_MIDDLE_FLOATING_CENTER, null, null, null, TileMap.Tiles.PURPLE_GRASS_TOP_FLOATING_LEFT, TileMap.Tiles.PURPLE_DIRT_MIDDLE_RIGHT, null, TileMap.Tiles.PURPLE_GRASS_TOP_FLOATING_LEFT, TileMap.Tiles.PURPLE_DIRT_MIDDLE_RIGHT, null, null, null, TileMap.Tiles.PURPLE_DIRT_MIDDLE_FLOATING_CENTER, null, null, null, null, TileMap.Tiles.PURPLE_DIRT_MIDDLE_FLOATING_CENTER, null },
        { TileMap.Tiles.PURPLE_DIRT_MIDDLE_CENTER, TileMap.Tiles.PURPLE_DIRT_MIDDLE_CENTER, TileMap.Tiles.PURPLE_DIRT_MIDDLE_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_FLOATING_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_FLOATING_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_FLOATING_RIGHT, null, TileMap.Tiles.PURPLE_DIRT_MIDDLE_FLOATING_CENTER, null, TileMap.Tiles.PURPLE_GRASS_TOP_FLOATING_LEFT, TileMap.Tiles.PURPLE_DIRT_BOTTOM_RIGHT, null, null, null, null, TileMap.Tiles.PURPLE_DIRT_MIDDLE_FLOATING_CENTER, null, null, null, null, null, TileMap.Tiles.PURPLE_GRASS_TOP_FLOATING_LEFT, TileMap.Tiles.PURPLE_DIRT_MIDDLE_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_RIGHT, null, null, null, TileMap.Tiles.PURPLE_DIRT_MIDDLE_FLOATING_CENTER, null },
        { TileMap.Tiles.PURPLE_DIRT_MIDDLE_CENTER, TileMap.Tiles.PURPLE_DIRT_MIDDLE_CENTER, TileMap.Tiles.PURPLE_DIRT_MIDDLE_RIGHT, null, null, null, null, TileMap.Tiles.PURPLE_DIRT_MIDDLE_FLOATING_CENTER, null, null, null, null, null, TileMap.Tiles.PURPLE_GRASS_TOP_FLOATING_LEFT, TileMap.Tiles.PURPLE_GRASS_TOP_FLOATING_CENTER, TileMap.Tiles.PURPLE_DIRT_MIDDLE_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_RIGHT, null, null, null, null, null, TileMap.Tiles.PURPLE_DIRT_MIDDLE_LEFT, TileMap.Tiles.PURPLE_DIRT_MIDDLE_RIGHT, null, null, null, TileMap.Tiles.PURPLE_DIRT_MIDDLE_FLOATING_CENTER, null },
        { TileMap.Tiles.PURPLE_DIRT_MIDDLE_CENTER, TileMap.Tiles.PURPLE_DIRT_MIDDLE_CENTER, TileMap.Tiles.PURPLE_DIRT_MIDDLE_RIGHT, null, null, null, null, TileMap.Tiles.PURPLE_DIRT_MIDDLE_LEFT, TileMap.Tiles.PURPLE_GRASS_TOP_RIGHT, null, null, null, null, TileMap.Tiles.PURPLE_GRAVESTONE, null, TileMap.Tiles.PURPLE_DIRT_MIDDLE_LEFT, TileMap.Tiles.PURPLE_DIRT_MIDDLE_RIGHT, null, null, TileMap.Tiles.PURPLE_GRAVESTONE, null, null, TileMap.Tiles.PURPLE_DIRT_MIDDLE_LEFT, TileMap.Tiles.PURPLE_DIRT_MIDDLE_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_RIGHT, null, null, TileMap.Tiles.PURPLE_DIRT_MIDDLE_FLOATING_CENTER, null },
        { TileMap.Tiles.PURPLE_DIRT_BOTTOM_CENTER, TileMap.Tiles.PURPLE_DIRT_BOTTOM_CENTER, TileMap.Tiles.PURPLE_DIRT_BOTTOM_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_FLOATING_RIGHT, null, TileMap.Tiles.PURPLE_GRASS_TOP_FLOATING_LEFT, TileMap.Tiles.PURPLE_GRASS_TOP_FLOATING_CENTER, TileMap.Tiles.PURPLE_DIRT_BOTTOM_CENTER, TileMap.Tiles.PURPLE_DIRT_BOTTOM_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_FLOATING_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_FLOATING_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_FLOATING_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_FLOATING_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_FLOATING_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_FLOATING_CENTER, TileMap.Tiles.PURPLE_DIRT_BOTTOM_CENTER, TileMap.Tiles.PURPLE_DIRT_BOTTOM_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_FLOATING_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_FLOATING_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_FLOATING_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_FLOATING_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_FLOATING_CENTER, TileMap.Tiles.PURPLE_DIRT_BOTTOM_CENTER, TileMap.Tiles.PURPLE_DIRT_BOTTOM_CENTER, TileMap.Tiles.PURPLE_DIRT_BOTTOM_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_FLOATING_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_FLOATING_CENTER, TileMap.Tiles.PURPLE_DIRT_BOTTOM_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_FLOATING_CENTER },
        { null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null },
        { null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null },
        { null, TileMap.Tiles.PURPLE_GRAVESTONE, null, null, null, null, null, null, null, null, TileMap.Tiles.PURPLE_GRASS_TOP_ALONE, null, null, null, null, null, null, null, null, TileMap.Tiles.PURPLE_GRASS_TOP_ALONE, null, null, null, null, null, null, null, null, TileMap.Tiles.ENDING_GLOBE },
        { TileMap.Tiles.PURPLE_GRASS_TOP_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_CENTER, TileMap.Tiles.PURPLE_GRASS_TOP_CENTER },
    };

    public Vector2 SpawnLocation { get; set; } = new Vector2(1, 1);
    public List<Enemy> Enemies { get; set; } = new();
    public Texture2D Background { get; set; }
    
    public Level2(GameManager game)
    {
        _game = game;
        Background = _game.RootGame.Content.Load<Texture2D>("level2background");
        
        Enemies.Add(new Enemy1(_game, new Vector2(225, 90), new Vector2(600, 90)));
        Enemies.Add(new Enemy2(_game, new Vector2(655, 40), new Vector2(1460, 40)));
        Enemies.Add(new Enemy3(_game, new Vector2(590, 750), new Vector2(930,750)));
        Enemies.Add(new Enemy1(_game, new Vector2(1290, 290), new Vector2(1520, 290)));
        Enemies.Add(new Enemy2(_game, new Vector2(1100, 750), new Vector2(1380, 750)));
        Enemies.Add(new Enemy1(_game, new Vector2(190, 595), new Vector2(350, 595)));
        Enemies.Add(new Enemy2(_game, new Vector2(700, 955), new Vector2(1185, 955)));
    }
}